version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: courtmate_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rootpassword # Geliştirme ortamı için basit bir şifre
      POSTGRES_DB: courtmate
    ports:
      - "5432:5432"
    volumes:
      - courtmate_pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: courtmate_redis
    restart: always
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: courtmate_rabbitmq
    restart: always
    ports:
      - "5672:5672"   # RabbitMQ port
      - "15672:15672" # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  courtmate_pgdata: