version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: courtmate_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rootpassword # Geliştirme ortamı için basit bir şifre
      POSTGRES_DB: courtmate
    ports:
      - "5432:5432"
    volumes:
      - courtmate_pgdata:/var/lib/postgresql/data

volumes:
  courtmate_pgdata: